services:
  crm-partners:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./crm_partners_files:/crm_partners_files
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database


  database:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass