services:
  crm-partners:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./crm_partners_files:/crm_partners_files
#    environment:
#      - DB_HOST=${DB_HOST}
#      - DB_NAME=${DB_NAME}
#      - DB_USER=${DB_USER}
#      - DB_PASS=${DB_PASS}
#      - BOT_TOKEN_LINK_GENERATOR=${BOT_TOKEN_LINK_GENERATOR}
#      - GOOGLE_SPREADSHEETS_TABLE_ID=${GOOGLE_SPREADSHEETS_TABLE_ID}
#      - PROJECT_ID=${PROJECT_ID}
#      - PRIVATE_KEY_ID=${PRIVATE_KEY_ID}
#      - PRIVATE_KEY=${PRIVATE_KEY}
#      - CLIENT_EMAIL=${CLIENT_EMAIL}
#      - CLIENT_ID=${CLIENT_ID}
#      - AUTH_URI=${AUTH_URI}
#      - TOKEN_URI=${TOKEN_URI}
#      - AUTH_PROVIDER=${AUTH_PROVIDER}
#      - CLIENT=${CLIENT}
#      - UNIVERSE_DOMAIN=${UNIVERSE_DOMAIN}

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - database


  database:
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass