# Generated by Django 5.0.2 on 2024-03-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_link_link_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link_source',
            new_name='source_type',
        ),
    ]
