# Generated by Django 5.0.2 on 2024-03-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_rename_link_source_link_source_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterField(
            model_name='link',
            name='link_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name of the link'),
        ),
    ]
