# Generated by Django 5.0.2 on 2024-03-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_alter_link_options_alter_link_link_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='source_type',
        ),
        migrations.AddField(
            model_name='link',
            name='category',
            field=models.CharField(default='От компании к подрядчику', max_length=255, verbose_name="Link's category"),
            preserve_default=False,
        ),
    ]
