# Generated by Django 5.0.2 on 2024-03-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_remove_link_source_type_link_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-id'], 'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
    ]
